### ISSUE TITLE
Teleport capability not included

### ISSUE THREAD

**Issue by joosh98** [Ellamental2/PTUTokenIcons#3]
![image](https://user-images.githubusercontent.com/76598711/178140550-e6c8d6ab-0f7e-4d56-8f52-34029d922647.png)

Teleport capability does not show

**Comment by Ellamental2** [comment]
Teleport now included in the icons 

![image](https://user-images.githubusercontent.com/43385250/178348523-ccab7aa2-5af9-4df7-b522-be9805275662.png)
